#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Karya.Droid.Resource", IsApplication=true)]

namespace Karya.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Attendancepic = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Board45 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendarpic = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chat = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int forum = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int info = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int karya = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logopic = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int magicwand = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Pencil45 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int photocamera = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settings = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int subject = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int timetable = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060038
			public const int Text = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int Text1 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int Text2 = 2131099706;
			
			// aapt resource value: 0x7f060001
			public const int Titletext = 2131099649;
			
			// aapt resource value: 0x7f060055
			public const int antonymtext = 2131099733;
			
			// aapt resource value: 0x7f060022
			public const int attendbutton = 2131099682;
			
			// aapt resource value: 0x7f06002e
			public const int attendedbut = 2131099694;
			
			// aapt resource value: 0x7f06000e
			public const int attlistview = 2131099662;
			
			// aapt resource value: 0x7f06002f
			public const int bunkedbut = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int bunkedtext = 2131099690;
			
			// aapt resource value: 0x7f06004b
			public const int bunkedtext1 = 2131099723;
			
			// aapt resource value: 0x7f060015
			public const int butev = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int buttonclick = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int cancelbut = 2131099660;
			
			// aapt resource value: 0x7f060058
			public const int categorytext = 2131099736;
			
			// aapt resource value: 0x7f060003
			public const int datePicker1 = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int datepick = 2131099661;
			
			// aapt resource value: 0x7f060031
			public const int datetext = 2131099697;
			
			// aapt resource value: 0x7f060010
			public const int delattbut = 2131099664;
			
			// aapt resource value: 0x7f060037
			public const int delbut = 2131099703;
			
			// aapt resource value: 0x7f060034
			public const int delevbut = 2131099700;
			
			// aapt resource value: 0x7f060016
			public const int delevsbut = 2131099670;
			
			// aapt resource value: 0x7f060044
			public const int delsubsbut = 2131099716;
			
			// aapt resource value: 0x7f060002
			public const int desctext = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int detailviewbut = 2131099663;
			
			// aapt resource value: 0x7f060036
			public const int editbut = 2131099702;
			
			// aapt resource value: 0x7f06003f
			public const int emailtext = 2131099711;
			
			// aapt resource value: 0x7f06001f
			public const int eventbutton = 2131099679;
			
			// aapt resource value: 0x7f060014
			public const int eventlist = 2131099668;
			
			// aapt resource value: 0x7f060046
			public const int eventnumtext = 2131099718;
			
			// aapt resource value: 0x7f060035
			public const int filelistview = 2131099701;
			
			// aapt resource value: 0x7f060045
			public const int filenumtext = 2131099717;
			
			// aapt resource value: 0x7f060040
			public const int gobut = 2131099712;
			
			// aapt resource value: 0x7f060019
			public const int imageView1 = 2131099673;
			
			// aapt resource value: 0x7f060012
			public const int imageclickbut = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060025
			public const int linearLayout2 = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int linearLayout3 = 2131099688;
			
			// aapt resource value: 0x7f06004f
			public const int linearLayout4 = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int linearLayout5 = 2131099729;
			
			// aapt resource value: 0x7f060053
			public const int linearLayout6 = 2131099731;
			
			// aapt resource value: 0x7f060056
			public const int linearLayout7 = 2131099734;
			
			// aapt resource value: 0x7f060018
			public const int linearLayouta = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayoutb = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayoutc = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int linearLayoutd = 2131099680;
			
			// aapt resource value: 0x7f06004d
			public const int magicwordtext = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int meaningtext = 2131099726;
			
			// aapt resource value: 0x7f06002d
			public const int noclassbut = 2131099693;
			
			// aapt resource value: 0x7f060011
			public const int relativeLayout1 = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int relativeLayoutrl = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int repeatspin = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int repeattext = 2131099655;
			
			// aapt resource value: 0x7f06004c
			public const int resetsubatbut = 2131099724;
			
			// aapt resource value: 0x7f060008
			public const int saveevbut = 2131099656;
			
			// aapt resource value: 0x7f06003b
			public const int signinbut = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int signupbut = 2131099708;
			
			// aapt resource value: 0x7f060047
			public const int slotholdergrid = 2131099719;
			
			// aapt resource value: 0x7f06002b
			public const int statusondatetext = 2131099691;
			
			// aapt resource value: 0x7f06000b
			public const int subadd1but = 2131099659;
			
			// aapt resource value: 0x7f060043
			public const int subaddbut = 2131099715;
			
			// aapt resource value: 0x7f060033
			public const int subgrouptext = 2131099699;
			
			// aapt resource value: 0x7f06001c
			public const int subjectbutton = 2131099676;
			
			// aapt resource value: 0x7f060042
			public const int sublist = 2131099714;
			
			// aapt resource value: 0x7f060009
			public const int subnametext = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int subspin = 2131099653;
			
			// aapt resource value: 0x7f060048
			public const int subspinner = 2131099720;
			
			// aapt resource value: 0x7f060052
			public const int synonymtext = 2131099730;
			
			// aapt resource value: 0x7f06000a
			public const int teachernametext = 2131099658;
			
			// aapt resource value: 0x7f060041
			public const int textItem = 2131099713;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060023
			public const int textView2 = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int textView3 = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int textView4 = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int textView5 = 2131099692;
			
			// aapt resource value: 0x7f060054
			public const int textView6 = 2131099732;
			
			// aapt resource value: 0x7f060057
			public const int textView7 = 2131099735;
			
			// aapt resource value: 0x7f06003d
			public const int textlink = 2131099709;
			
			// aapt resource value: 0x7f060004
			public const int timePicker1 = 2131099652;
			
			// aapt resource value: 0x7f06001e
			public const int timetablebutton = 2131099678;
			
			// aapt resource value: 0x7f060032
			public const int timetext = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int titletext = 2131099696;
			
			// aapt resource value: 0x7f060027
			public const int totalattendtext = 2131099687;
			
			// aapt resource value: 0x7f06004a
			public const int totalattendtext1 = 2131099722;
			
			// aapt resource value: 0x7f060024
			public const int totalinputtext = 2131099684;
			
			// aapt resource value: 0x7f060049
			public const int totalinputtext1 = 2131099721;
			
			// aapt resource value: 0x7f060050
			public const int usagetext = 2131099728;
			
			// aapt resource value: 0x7f06003e
			public const int usernametext = 2131099710;
			
			// aapt resource value: 0x7f060021
			public const int vocabbutton = 2131099681;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Addeventlayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Addsubjectlayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Attendancelayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Clicklayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Eventlayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Homelayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Inattendancelayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Ineventlayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Insubjectlayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int listview = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Loginpage = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Settinglayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int simplespinnerlayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Subjectlayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Subjecttimetablelayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Timetablelayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Totalattendancelayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Vocablayout = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
